theme: jekyll-theme-cayman
title: Onlyaim
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
github:
  is_project_page: true
  repository_url: http://bioconductor.org/packages/DEsingle
  zip_url: http://bioconductor.org/packages/DEsingle
  tar_url: http://bioconductor.org/packages/DEsingle
  
