theme: jekyll-theme-cayman
title: Onlyaim
description: Independent Spirit, Liberal Thoughts
show_downloads: true
github:
  is_project_page: true
  repository_url: https://miaozhun.github.io/DEsingle/
  zip_url: http://bioconductor.org/packages/DEsingle
  tar_url: https://github.com/miaozhun/ImputeSingle
  
